version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:11

jobs:

  # generates a static website and store the outcome on the workspace
  build:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          key: yarn-cache-{{ arch }}
      - restore_cache:
          key: node-modules-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile
      - run: yarn build

      - save_cache:
          key: yarn-cache-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-modules-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: .
          paths:
            - ./*

  # given a static website was built and stored on workspace, deploy it to netlify
  deploy:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .

      # this will work only if NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID are defined on the environment
      - run: yarn run netlify --telemetry-disable
      - run: yarn run netlify deploy --dir=".next/server/static/`cat .next/BUILD_ID`/pages" --prod

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
