version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
    steps:
      - checkout

      - restore_cache:
          key: yarn-cache-{{ arch }}
      - restore_cache:
          key: node-modules-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile
      - run: yarn build

      - save_cache:
          key: yarn-cache-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-modules-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
